language: ruby
rvm:
  - 2.3.1

os:
  - linux
  - osx

before_script:
  - gem install bashcov
  - gem install coveralls

script:
  - bashcov --skip-uncovered -- ./test.sh bin/elm-new && coveralls push
