.Dd June 12, 2016
.Dt ELM-NEW 1
.Os
.Sh NAME
.Nm elm-new
.Nd generate a file hierarchy for a new Elm project
.Sh SYNOPSIS
.Nm
.Op Fl b | Fl h | Fl V
.Op Ar path
.Sh DESCRIPTION
The
.Nm
utility creates a directory tree in the provided
.Ar path
, or in the current directory by default.
The generated project will be using Html.App.program
if no options provided.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl b, -beginner
Generates a new Elm program using Html.App.beginnerProgram.
.It Fl h, -help
Prints the synopsis.
.It Fl V, -version
Prints the currently installed version.
.El
