.Dd November 18, 2016
.Dt ELM-NEW 1
.Os
.Sh NAME
.Nm elm-new
.Nd generate a file hierarchy for a new Elm project
.Sh SYNOPSIS
.Nm
.Op Ar path
.Op Fl b | Fl h | Fl V
.Sh DESCRIPTION
The
.Nm
utility creates a directory tree in the provided
.Ar path
, or in the current directory by default.
The generated project will be using Browser.document
if no options provided.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl b, -beginner
Generates an Elm program using Browser.sandbox.
.It Fl -hello-world
Generates an Elm program that prints "Hello, world!".
.It Fl -navigation
Generates an Elm program using Browser.application.
.It Fl h, -help
Prints the synopsis.
.It Fl V, -version
Prints the currently installed version.
.El
